import { useState } from 'react';

function App() {
  const [userType, setUserType] = useState<'client' | 'delivery' | 'transport'>('client');
    const [formData, setFormData] = useState({
        firstName: '',
            lastName: '',
                email: '',
                    password: '',
                        phone: '',
                            familyAddress: '',
                                companyName: '',
                                    contactPhone: '',
                                        routesAvailable: ''
                                          });
                                            const [message, setMessage] = useState('');

                                              const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
                                                  const { name, value } = e.target;
                                                      setFormData(prev => ({ ...prev, [name]: value }));
                                                        };

                                                          const handleSubmit = async (e: React.FormEvent) => {
                                                              e.preventDefault();
                                                                  setMessage('Envoi en cours...');

                                                                      let endpoint = '';
                                                                          let payload: any = {};

                                                                              if (userType === 'client') {
                                                                                    endpoint = '/api/v1/auth/register/client';
                                                                                          payload = {
                                                                                                  firstName: formData.firstName,
                                                                                                          lastName: formData.lastName,
                                                                                                                  email: formData.email,
                                                                                                                          password: formData.password
                                                                                                                                };
                                                                                                                                    } else if (userType === 'delivery') {
                                                                                                                                          endpoint = '/api/v1/auth/register/delivery';
                                                                                                                                                payload = {
                                                                                                                                                        firstName: formData.firstName,
                                                                                                                                                                lastName: formData.lastName,
                                                                                                                                                                        email: formData.email,
                                                                                                                                                                                password: formData.password,
                                                                                                                                                                                        phone: formData.phone,
                                                                                                                                                                                                familyAddress: formData.familyAddress
                                                                                                                                                                                                      };
                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                endpoint = '/api/v1/auth/register/transport';
                                                                                                                                                                                                                      payload = {
                                                                                                                                                                                                                              companyName: formData.companyName,
                                                                                                                                                                                                                                      contactEmail: formData.email,
                                                                                                                                                                                                                                              contactPhone: formData.contactPhone,
                                                                                                                                                                                                                                                      routesAvailable: formData.routesAvailable.split(',').map((r: string) => r.trim())
                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                          const response = await fetch('https://faso-livraison-backend-be6y.onrender.com' + endpoint, {
                                                                                                                                                                                                                                                                                  method: 'POST',
                                                                                                                                                                                                                                                                                          headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                  body: JSON.stringify(payload)
                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                              if (response.ok) {
                                                                                                                                                                                                                                                                                                                      setMessage('✅ Inscription réussie !');
                                                                                                                                                                                                                                                                                                                              setFormData({
                                                                                                                                                                                                                                                                                                                                        firstName: '', lastName: '', email: '', password: '', phone: '', familyAddress: '',
                                                                                                                                                                                                                                                                                                                                                  companyName: '', contactPhone: '', routesAvailable: ''
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                        const errorData = await response.json().catch(() => ({}));
                                                                                                                                                                                                                                                                                                                                                                                const errorMsg = errorData?.error?.fieldErrors
                                                                                                                                                                                                                                                                                                                                                                                          ? Object.values(errorData.error.fieldErrors).flat().join(', ')
                                                                                                                                                                                                                                                                                                                                                                                                    : 'Veuillez réessayer';
                                                                                                                                                                                                                                                                                                                                                                                                            setMessage('❌ Erreur : ' + errorMsg);
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                            setMessage('❌ Impossible de contacter le serveur');
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif', maxWidth: '600px', margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <h1 style={{ textAlign: 'center', color: '#2E7D32' }}>Faso Livraison</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ textAlign: 'center' }}>Inscrivez-vous en tant que :</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ display: 'flex', gap: '10px', justifyContent: 'center', marginBottom: '20px', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setUserType('client')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: '10px', backgroundColor: userType === 'client' ? '#4CAF50' : '#e0e0e0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: userType === 'client' ? 'white' : 'black', border: 'none', borderRadius: '5px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Client
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setUserType('delivery')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: '10px', backgroundColor: userType === 'delivery' ? '#4CAF50' : '#e0e0e0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: userType === 'delivery' ? 'white' : 'black', border: 'none', borderRadius: '5px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Livreur
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setUserType('transport')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: '10px', backgroundColor: userType === 'transport' ? '#4CAF50' : '#e0e0e0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: userType === 'transport' ? 'white' : 'black', border: 'none', borderRadius: '5px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Société
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {(userType === 'client' || userType === 'delivery') && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="firstName" placeholder="Prénom" value={formData.firstName} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="lastName" placeholder="Nom" value={formData.lastName} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="email" type="email" placeholder="Email" value={formData.email} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="password" type="password" placeholder="Mot de passe" value={formData.password} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {userType === 'delivery' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="phone" placeholder="Numéro de téléphone" value={formData.phone} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="familyAddress" placeholder="Adresse d'un membre de la famille" value={formData.familyAddress} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {userType === 'transport' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="companyName" placeholder="Nom de la société" value={formData.companyName} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="email" type="email" placeholder="Email de contact" value={formData.email} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="contactPhone" placeholder="Téléphone de contact" value={formData.contactPhone} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="routesAvailable" placeholder="Villes desservies (ex: Ouagadougou,Bobo)" value={formData.routesAvailable} onChange={handleChange} required style={{ display: 'block', width: '100%', padding: '10px', margin: '8px 0' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="submit" style={{ width: '100%', padding: '12px', backgroundColor: '#2E7D32', color: 'white', border: 'none', borderRadius: '5px', fontSize: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    S'inscrire
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {message && <p style={{ textAlign: 'center', marginTop: '15px', color: message.includes('✅') ? 'green' : 'red' }}>{message}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default App;