import { useState } from 'react';

function App() {
  const [userType, setUserType] = useState<'client' | 'delivery' | 'transport'>('client');
    const [formData, setFormData] = useState({
        name: '',
            surname: '',
                email: '',
                    phone: '',
                        familyAddress: '',
                            companyName: '',
                                contactPhone: '',
                                    routesAvailable: ''
                                      });
                                        const [message, setMessage] = useState('');

                                          const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
                                              const { name, value } = e.target;
                                                  setFormData(prev => ({ ...prev, [name]: value }));
                                                    };

                                                      const handleSubmit = async (e: React.FormEvent) => {
                                                          e.preventDefault();
                                                              setMessage('Envoi en cours...');

                                                                  let endpoint = '';
                                                                      let payload: Record<string, any> = {};

                                                                          if (userType === 'client') {
                                                                                endpoint = '/api/v1/auth/register/client';
                                                                                      payload = {
                                                                                              name: formData.name,
                                                                                                      surname: formData.surname,
                                                                                                              email: formData.email
                                                                                                                    };
                                                                                                                        } else if (userType === 'delivery') {
                                                                                                                              endpoint = '/api/v1/auth/register/delivery';
                                                                                                                                    payload = {
                                                                                                                                            name: formData.name,
                                                                                                                                                    surname: formData.surname,
                                                                                                                                                            email: formData.email,
                                                                                                                                                                    phone: formData.phone,
                                                                                                                                                                            familyAddress: formData.familyAddress
                                                                                                                                                                                  };
                                                                                                                                                                                      } else {
                                                                                                                                                                                            endpoint = '/api/v1/auth/register/transport';
                                                                                                                                                                                                  payload = {
                                                                                                                                                                                                          companyName: formData.companyName,
                                                                                                                                                                                                                  contactEmail: formData.email,
                                                                                                                                                                                                                          contactPhone: formData.contactPhone,
                                                                                                                                                                                                                                  routesAvailable: formData.routesAvailable.split(',').map(r => r.trim())
                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                      const response = await fetch('https://faso-livraison-backend-be6y.onrender.com' + endpoint, {
                                                                                                                                                                                                                                                              method: 'POST',
                                                                                                                                                                                                                                                                      headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                              body: JSON.stringify(payload)
                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                          if (response.ok) {
                                                                                                                                                                                                                                                                                                  setMessage('✅ Inscription réussie !');
                                                                                                                                                                                                                                                                                                          setFormData({
                                                                                                                                                                                                                                                                                                                    name: '',
                                                                                                                                                                                                                                                                                                                              surname: '',
                                                                                                                                                                                                                                                                                                                                        email: '',
                                                                                                                                                                                                                                                                                                                                                  phone: '',
                                                                                                                                                                                                                                                                                                                                                            familyAddress: '',
                                                                                                                                                                                                                                                                                                                                                                      companyName: '',
                                                                                                                                                                                                                                                                                                                                                                                contactPhone: '',
                                                                                                                                                                                                                                                                                                                                                                                          routesAvailable: ''
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                const errorText = await response.text();
                                                                                                                                                                                                                                                                                                                                                                                                                        setMessage('❌ Erreur : ' + (errorText || 'Veuillez réessayer'));
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                        setMessage('❌ Impossible de contacter le serveur');
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif', maxWidth: '600px', margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h1 style={{ textAlign: 'center', color: '#2E7D32' }}>Faso Livraison</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{ textAlign: 'center' }}>Inscrivez-vous en tant que :</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: '10px', justifyContent: 'center', marginBottom: '20px', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {['client', 'delivery', 'transport'].map(type => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={type}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setUserType(type as typeof userType)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: userType === type ? '#4CAF50' : '#e0e0e0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: userType === type ? 'white' : 'black',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: '5px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {type === 'client' ? 'Client' : type === 'delivery' ? 'Livreur' : 'Société'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {userType === 'client' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="name" placeholder="Prénom" value={formData.name} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="surname" placeholder="Nom" value={formData.surname} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="email" type="email" placeholder="Email" value={formData.email} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {userType === 'delivery' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="name" placeholder="Prénom" value={formData.name} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="surname" placeholder="Nom" value={formData.surname} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="email" type="email" placeholder="Email" value={formData.email} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="phone" placeholder="Numéro de téléphone" value={formData.phone} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="familyAddress" placeholder="Adresse d'un membre de la famille" value={formData.familyAddress} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {userType === 'transport' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input name="companyName" placeholder="Nom de la société" value={formData.companyName} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input name="email" type="email" placeholder="Email de contact" value={formData.email} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="contactPhone" placeholder="Téléphone de contact" value={formData.contactPhone} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input name="routesAvailable" placeholder="Villes desservies (ex: Ouagadougou,Bobo)" value={formData.routesAvailable} onChange={handleChange} required style={inputStyle} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="submit" style={{ width: '100%', padding: '12px', backgroundColor: '#2E7D32', color: 'white', border: 'none', borderRadius: '5px', fontSize: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                S'inscrire
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {message && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ textAlign: 'center', marginTop: '15px', color: message.includes('✅') ? 'green' : 'red' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const inputStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: 'block',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: '10px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  margin: '8px 0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default App;